---
- name: Create directories for templated files.
  include: "createdir.yml path={{ item.path }} mode={{ item.mode }}"
  with_filetree: "{{ dotfiles_template_path }}"
  when: dotfiles_template_path != None and item.state == "directory"

- name: Template files.
  template:
    src: "{{ item.src }}"
    dest: "/{{ item.path | replace('__HOME__', ansible_env.HOME) | ltrim('/') }}"
    mode: "{{ item.mode }}"
  with_filetree: "{{ dotfiles_template_path }}"
  when: dotfiles_template_path != None and item.state == "file" and item.path|basename != ".DS_Store"

- name: Create directories for symlinked files.
  include: "createdir.yml path={{ item.path }} mode={{ item.mode }}"
  with_filetree: "{{ dotfiles_file_path }}"
  when: dotfiles_file_path != None and item.state == "directory"

- name: Create symlinks.
  file:
    src: "{{ item.src }}"
    dest: "/{{ item.path | replace('__HOME__', ansible_env.HOME) | ltrim('/') }}"
    state: link
    force: yes
    mode: "{{ item.mode }}"
  with_filetree: "{{ dotfiles_file_path }}"
  when: dotfiles_file_path != None and item.state == "file" and item.path|basename != ".DS_Store"

- name: Check if .osx dotfile is present.
  stat:
    path: "{{ dotfiles_osx_file }}"
  register: osx_file
  when: dotfiles_osx_file != None

- name: Run .osx dotfile.
  shell: "{{ dotfiles_osx_file }} --no-restart"
  changed_when: false
  when: dotfiles_osx_file != None and osx_file.stat.exists == true
  become: true
