---
- name: Process templates.
  include: "template.yml path={{ item }}"
  with_items: "{{ dotfiles_template_paths }}"

- name: Process files.
  include: "file.yml path={{ item }}"
  with_items: "{{ dotfiles_file_paths }}"

- name: Process dotfiles.
  include: "dotfile.yml path={{ item }}"
  with_items: "{{ dotfiles_osx_files }}"
